---
- name: Ensure users exist
  hosts: all
  become: yes
  vars:
    users:
      - name: bob
        groups:
          - developer

  tasks:
    - name: Ensure required groups exist
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - developer

    - name: Ensure users are present
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups | default(omit) }}"
        state: present
      loop: "{{ users }}"
